### ISSUE TITLE
sensor fails on start

### ISSUE THREAD

**Issue by rutberg** [fredrikbaberg/ha-sensor-sl#22]
When following the instructions in the readme, including adding the custom component, I get the following results:

```
Wed Jan 16 2019 13:43:33 GMT+0100 (Central European Standard Time)

Update for sensor.sl_stureby fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
    await self.async_device_update()
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 349, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/sensor/sl.py", line 158, in update
    if self._enabled_sensor is None or sensor_state.state is STATE_ON:
AttributeError: 'NoneType' object has no attribute 'state'
```

This is my configuration.yaml
```
# Sensors
sensor:
  # Weather prediction
  - platform: yr
  - platform: sl
    name: stureby
    ri4key: MyAPIKEY
    siteid: 9164
    lines: 17, 18, 19
    direction: 1
    sensor: binary_sensor.test
```

**Comment by rutberg** [comment]
Realized the fault being with the `binary_sensor.test` and no instruction to also add the sensor to configuration.yaml

**Comment by theGurk** [comment]
> Realized the fault being with the binary_sensor.test and no instruction to also add the sensor to configuration.yaml

I can´t get it to work. How did you add it to the configuration.yaml file you mean?
